sudo: false
language: ruby
rvm:
  - 2.3.3
cache:
  bundler: true
  directories:
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10
bundler_args: --without test --jobs 3 --retry 3
before_install:
  - openssl aes-256-cbc -K $encrypted_40020334322c_key -iv $encrypted_40020334322c_iv -in id_rsa_rorlakr_rrails_guides_travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - gem install bundler
before_script:
  - echo -e "Host guides.rorlab.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bundle update
script: "cd guides && bundle exec rake guides:generate:html:ko:publish ALL=1 RAILS_VERSION=5.0.2"
branches:
  only:
    - guides-ko
